# dbt_projects/dbt_trino/profiles.yml
dbt_trino:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino-coordinator
      port: 8080
      user: trino
      schema: default
      catalog: postgresql